services:
    app:
      build: .
      image: collect:latest
      environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development
        - PYTHONUNBUFFERED=1
      container_name: collect
      command: flask run --host=0.0.0.0 --port 5000
      ports:
        - "5000:5000"
      volumes:
        - .:/app
