version: '3'
services:
    app:
      build: .
      image: collect:latest
      environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development
        - PYTHONUNBUFFERED=1
      container_name: collect
      command: flask run --host=0.0.0.0 --port 5000
      stdin_open: true
      tty: true
      ports:
        - "8085:5000"
      volumes:
        - .:/app
    node:
      build: 
        context: .
        dockerfile: ./Dockerfile_node
      image: collect:node
      container_name: node
      command: npx tailwindcss -i /app/static/src/input.css -o /app/static/css/main.css --watch
      stdin_open: true
      tty: true
      stop_grace_period: 0s
      volumes:
        - .:/app
